
# This script supplements the manuscript "Leveraging agent-based modeling and co-occurrence data to
# validate a generalized metabolic model of species interaction in the human gut microbiome" by 
# Jyoti Jyoti, Hannah Zoller, Wolfgang zu Castell, and Marc-Thorsten Hütt.

# This script takes as input
# - the files "cross_share_c.Rdata" and "cross_share_p.Rdata"
# (as being generated by BacArena_evaluation_CIs.R)
# - the genome-scale models of all 73 species (sorted by random set in the folders "random_set_models_[]")
# - the csv file "Cooccurance_HealthyLean.csv"
# - the Rdata files "share_matrix_set_[]_rn_[].Rdata" and "fracs_matrix_set_[]_rn_[].Rdata"
# (as being generated by BacArena_evaluation_CIs.Rdata)

# This script produces Supplementary Figures 3a and 5 of the manuscript 

# Written by Hannah Zoller, 2025


#Set working directory

work_folder <- "work_folder"
setwd(work_folder)

#Load packages

library(xlsx)
library(stringr)
library(matrixStats)
library(ggplot2)
library(Hmisc)
library(ppcor)


#Supplementary Figure 3: correlation between cross-feeding and shared feeding 

cross_share_c <- get(load("cross_share_c.Rdata"))
cross_share_p <- get(load("cross_share_p.Rdata"))

cols_mat <- matrix("grey",10,10)

for(i in 1:10){
  for(j in 1:10){
    if(cross_share_p[i,j]<=0.01){
      cols_mat[i,j] <- "darkred"
    }
  }
}

pdf("Correlation_cross_feeding_shared_feeding.pdf", paper = "a4r", width = 10)

par(mar = c(5.1, 5.7, 4.1, 2.1))

plot(1:9,cross_share_c[-1,1], cex = 2, cex.axis = 1.5, cex.lab = 2, xaxt = "n", col = cols_mat[2,], ylim = c(min(cross_share_c[-1,]),max(cross_share_c[-1,])), xlab = "", ylab = "")
axis(1, at = 1:9, labels = as.character(seq(0.1,0.9,0.1)), cex.axis = 1.55)
title(ylab = "correlation", cex.lab = 2, line = 4)
title(xlab = "richness level", cex.lab = 2, line = 4)
for(i in 2:10){
  points(1:9,cross_share_c[-1,i], col = cols_mat[-1,i], cex = 2)
}
legend(6,-0.05, bty = "n", cex = 2, pch = 1, col = c("darkred", "grey"), legend = c("significant", "non-significant"))

dev.off()


#Supplementary Figure 5: correlation between metabolic measures and co-occurrences 

interactions <- c("shared feeding", "crossfeeding")

co_occ <- read.csv("Cooccurance_HealthyLean.csv", header = TRUE, sep = "\t") 
co_occ <- co_occ[,-1]
rownames(co_occ) <- colnames(co_occ)
  
cross_share_p <- matrix(NA,10,10)
cross_share_c <- matrix(NA,10,10)

for(set_nr in 1:10){
  
  names <- list.files(paste("/random_set_models_",set_nr,sep=""), full.names = FALSE)
  names <- str_sub(names, end = -5)
  sp <- which(rownames(co_occ) %in% names)
  
  for(rn in 1:10){
    
    if(int==1){
      fracs <- get(load(paste("fracs_matrix_set",set_nr,"_rn",rn,".Rdata",sep="")))
    }else{
      fracs <- get(load(paste("share_matrix_set",set_nr,"_rn",rn,".Rdata",sep="")))
    }
    
    points_plot <- c()
    points_x <- c()
    for(k in 1:length(sp)){
      for(j in 1:length(sp)){
        if(k != j){
          jacc <- co_occ[k,j]
          points_plot <- c(points_plot,mean(c(fracs[k,j],fracs[j,k]), na.rm = TRUE))
          points_x <- c(points_x,jacc)
        }
      }
    }
    
    cor_pear <- cor.test(points_x,points_plot,method = "pearson")
    
    cross_share_c[rn,set_nr] <- cor_pear$estimate
    cross_share_p[rn,set_nr] <- cor_pear$p.value
    
  }
  
}

cols_mat <- matrix("grey",10,10)

for(i in 1:10){
  for(j in 1:10){
    if(cross_share_p[i,j]<=0.01){
      cols_mat[i,j] <- "darkgreen"
    }
  }
}

pdf(paste("Correlation_metabolic_measures_cooccurrances.pdf",sep=""), paper = "a4r", width = 10)

par(mar = c(5.1, 5.7, 4.4, 3.6), xpd = TRUE)

plot(1:9,cross_share_c[-1,1], cex = 2, cex.axis = 1.5, cex.lab = 2, xaxt = "n", col = cols_mat[2,], ylim = c(min(cross_share_c[-1,]),max(cross_share_c[-1,])), xlab = "", ylab = "")
axis(1, at = 1:9, labels = as.character(seq(0.1,0.9,0.1)), cex.axis = 1.55)
title(ylab = paste("correlation with ",interaction,sep=""), cex.lab = 2, line = 4)
title(xlab = "richness level", cex.lab = 2, line = 4)
for(i in 2:10){
  points(1:9,cross_share_c[-1,i], col = cols_mat[-1,i], cex = 2)
}
legend("topright", inset=c(-0.1, -0.225), bty = "n", cex = 2, pch = 1, col = c("darkgreen", "grey"), legend = c("significant", "non-significant"))

dev.off()
  
